Name:                   modeloperator
Namespace:              controller-40
CreationTimestamp:      Mon, 10 Nov 2025 09:54:28 +0000
Labels:                 app.kubernetes.io/managed-by=juju
                        model.juju.is/disable-webhook=true
                        operator.juju.is/name=modeloperator
                        operator.juju.is/target=model
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               operator.juju.is/name=modeloperator,operator.juju.is/target=model
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           model.juju.is/disable-webhook=true
                    operator.juju.is/name=modeloperator
                    operator.juju.is/target=model
  Service Account:  modeloperator
  Containers:
   juju-operator:
    Image:      ghcr.io/juju/jujud-operator:4.0-rc1
    Port:       17071/TCP (api)
    Host Port:  0/TCP (api)
    Command:
      /bin/sh
    Args:
      -c
      export JUJU_DATA_DIR=/var/lib/juju
      export JUJU_TOOLS_DIR=$JUJU_DATA_DIR/tools
      
      mkdir -p $JUJU_TOOLS_DIR
      cp /opt/jujud $JUJU_TOOLS_DIR/jujud
      
      exec $JUJU_TOOLS_DIR/jujud model --model-uuid=53864cf3-b4ee-4f1f-8b60-f405c1ebf396
      
    Environment:
      HTTP_PORT:          17071
      SERVICE_NAME:       modeloperator
      SERVICE_NAMESPACE:  controller-40
    Mounts:
      /var/lib/juju/agents/model-53864cf3-b4ee-4f1f-8b60-f405c1ebf396/template-agent.conf from modeloperator (rw,path="template-agent.conf")
  Volumes:
   modeloperator:
    Type:          ConfigMap (a volume populated by a ConfigMap)
    Name:          modeloperator
    Optional:      false
  Node-Selectors:  <none>
  Tolerations:     <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   modeloperator-5894577dd6 (1/1 replicas created)
Events:          <none>
