# format 2.0
tag: unit-controller-0
datadir: /var/lib/juju
transient-datadir: /var/run/juju
logdir: /var/log/juju
metricsspooldir: /var/lib/juju/metricspool
upgradedToVersion: 3.6.10
cacert: |
  -----BEGIN CERTIFICATE-----
  MIIEEjCCAnqgAwIBAgIUSIXGYjvUY47SS3KYCH76EyDHBCswDQYJKoZIhvcNAQEL
  BQAwITENMAsGA1UEChMESnVqdTEQMA4GA1UEAxMHanVqdS1jYTAeFw0yNTA5MTky
  MzEyNDVaFw0zNTA5MTkyMzE3NDVaMCExDTALBgNVBAoTBEp1anUxEDAOBgNVBAMT
  B2p1anUtY2EwggGiMA0GCSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQCtxFR6YVXk
  aya1No8/laWDoa0v5bnOL9ic1WuK0ka++mTlt5suXnQmFJ1zEx9600ohoRRCVHdB
  6Y2hn6dY0uSFsPskDjihj9aFfAfAsxBVL5ZObGjai915GpfflekHhRYQlq4pF/us
  XDv1iN63BvSGZlNB4U6GVxoa9gIJW+l/E7EXun2OfH9DblEB6KujOgvu+3HrMmBh
  BuT41p9/CWg+NQX5IknybsScQkpyfjyr/7FKZbHb4dNNqPbKkxCFH/5BUmWE0RuK
  9WE9Xm1BhDWlI+C+Vya/jXKw4skxMo+SmkWUk9pKZfGXDltnug6x4wS/ertOtIYT
  6D/oZLRr+3VtzGie5VcR3LlqTFRn2f54glHnPKbtq4wvEWx6HTCcGvBaeQ5JiLea
  Yo/oT5QJ4MLRcWvlCh/bC6OeG+ybJ1LpgLmzSLNn9ED6jhQO7Y4nVvyI9XzZ0T3B
  AQZ38dUl48HDLJ2ZoEHKd9ypdN3GazbgTK3ByBddnXK13mZAIff3lZECAwEAAaNC
  MEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFKDn
  upfFcASM62bLaYDojRM3BiVPMA0GCSqGSIb3DQEBCwUAA4IBgQB9mtCd/NLcrpUo
  Y6DiSyFMGLd6a/ULsP05wSvzNpfGOOaoHrQQaFt3Lay/mQY0XfJ8II1Y1Vp3K3PM
  CDrYlkMt0d+Ne5PUrDYhtWR57xlpQQqYQGeBRbfezxhiXIhs0uK/vVHj5vOfLhLl
  X6UtXsqPlwVfyRjCI3kRQS4T7SwFF6v0OfBG9sWLFtgEt4aIGVGc1ts2sTgMgt2V
  Ff7vvH5/LHs6RiFVFRBrMWI4JRUqtwz/fdQUgEqCyTLwbb7+nFmxY0L8e1ATjQP8
  NOpkiNrXVUR5G5krqRg+uU6qWG/za+Q807VztiKI7eLDhjGX8xjy+GvhtF1xK90a
  8e9PxUlwgdMHuIuCeNVufn9/N8uRITSB+plJg/a8NINhVzffVAlnYYtZjQXieaGW
  Tgi/ykuJdBUI24SqLQX2rBXCx8T2KP/jwH9y8gr6Ss3cxAs68hdCzBR2yP+2dqFW
  lBhShvcDrGX5jL4lHUCfsNgxBEkX8Tzvc3E2DcOP7yi8BD6Z128=
  -----END CERTIFICATE-----
controller: controller-64475a48-50d7-40b1-891d-f84d278a2d30
model: model-7b60ed78-1f35-4791-8bc5-ab8cfe0b1a9f
apiaddresses:
- localhost:17070
apipassword: uPP2CjgZPHk/aa3DHkXX3Y3o
oldpassword: uPP2CjgZPHk/aa3DHkXX3Y3o
values: {}
agent-logfile-max-size: 0
agent-logfile-max-backups: 0
